[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "machine-learning"
version = 1.0.0
requires-python = ">= 3.12"
dependencies = [
    "numpy >= 2.2.0"    
]
authors = [{name = "Giovanni Abati", email = "gioabati@gmail.com"}]